### ISSUE TITLE
Update existing bucket using this module

### ISSUE THREAD

**Issue by Sandy1438** [terraform-aws-modules/terraform-aws-s3-bucket#106]
s3 source bucket is already existing in aws.
Now I want to use this module to update the replication rules on it as well as create new replica bucket to achieve s3 bucket replication. Is it possible to achieve this  using this replication module?

**Comment by antonbabenko** [comment]
Yes, it is possible. You will need to import the S3 bucket using [`terraform import`](https://www.terraform.io/docs/cli/import/index.html) and then customize replication configuration in `module` block.

If you have questions about `terraform import` or generic Terraform question, please ask on [discuss.hashicorp.com](https://discuss.hashicorp.com).
