### ISSUE TITLE
BUG: Invalid count argument

### ISSUE THREAD

**Issue by e-moshaya** [terraform-aws-modules/terraform-aws-s3-bucket#11]
This change https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/10 broke my current use of this module.

```
  on .terraform/modules/example/main.tf line 221, in resource "aws_s3_bucket_policy" "this":
 221:   count = var.create_bucket && (var.attach_elb_log_delivery_policy || var.policy != null) ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

make: *** [plan-without-prep] Error 1
```

I believe this is because I've passing the policy via data aws_iam_policy_document.

```
module "bucket" {
  source        = "git@github.com:terraform-aws-modules/terraform-aws-s3-bucket.git?ref=v1.2.0"
  create_bucket = var.enable ? true : false

  bucket = local.bucket_name
  region = var.default_region
  policy = element(
    concat(
      data.aws_iam_policy_document.this.*.json,
      [""],
    ),
    0,
  )
}
```

**Comment by antonbabenko** [comment]
Hi @e-moshaya !

You have this issue because you are referencing to non-computed resources inside of the policy (eg, bucket name).

I have updated the example to demonstrate how this can be used, see commit https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/commit/0d96e805c8db584dfa79bc2d40e25c52e2f1482f .

If problem persists, please show the source of `aws_iam_policy_document.this`.

**Comment by e-moshaya** [comment]
@antonbabenko please see the aws_iam_document policy below:

```
data "aws_iam_policy_document" "this" {
  count = var.enable ? 1 : 0
  statement {
    sid = "1"

    actions = [
      "s3:PutObject"
    ]

    resources = [
      "arn:aws:s3:::${local.github_primary_backup_bucket_name}/*",
    ]

    principals {
      type        = "AWS"
      identifiers = [element(concat(aws_iam_role.this.*.arn, list("")), 0)]
    }
  }
}
```

my point is that this was working fine prior to v1.1.0 because policy was added to a resource count condition ```var.policy != null```

Unfortunately, I can't use your example for setting s3 bucket policies as the principals is using wildcard access.. We operate a tight security setup and only allow access via least privilege iam roles/users. This means the iam role arn is not computed for the count condition.

**Comment by antonbabenko** [comment]
[v1.4.0](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/releases/v1.4.0) has been released.

`attach_policy = true` should be added.
