### ISSUE TITLE
Control S3 Bucket creation using certain  properties (Using CI Setup in Gitlab)

### ISSUE THREAD

**Issue by vikram-yerneni** [terraform-aws-modules/terraform-aws-s3-bucket#120]
## Is your request related to a new offering from AWS?
Nope

## Is your request related to a problem? Please describe.
I do have a module that basically creates a S3 bucket (using typical terraform `resource "aws_s3_bucket"`) with given terraform code that includes properties like "lifecycle_rule, server_side_encryption_configuration & logging" added in my main.tf file and we use Gitlab for the CI setup. 
However, I am trying to setup my Gitlab merge request process only goes through when ONLY RUNS WHEN THE ABOVE PROPERTIES ARE ADDED TO THE MAIN.TF FILE. I am not sure if this can be controlled at `Terraform plan `level or even before.
Anyone here in the community set this type of setup before? 

## Describe the solution you'd like.
Control terraform plan success from gitlab-ci.yml file

## Describe alternatives you've considered.
N/A

## Additional context
N/A

**Comment by antonbabenko** [comment]
I am not sure this is the best place to ask such questions here. I recommend you to ask on https://discuss.hashicorp.com where generic Terraform questions are more likely to be answered than here.

Thank you!

**Comment by vikram-yerneni** [comment]
Sure @antonbabenko . Thanks man
