### ISSUE TITLE
Boolean parameter for TLS v1.2 policy

### ISSUE THREAD

**Issue by aiell0** [terraform-aws-modules/terraform-aws-s3-bucket#125]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
No

## Describe the solution you'd like.
A boolean parameter to force users to use TLS version 1.2 when accessing the bucket.

## Describe alternatives you've considered.
My current workaround is to just create an external policy and attach it to the bucket, but felt that this is a common enough need that it could be a boolean parameter.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.13.0 :tada:
