### ISSUE TITLE
Enable Amazon EventBridge notifications in S3

### ISSUE THREAD

**Issue by igor-pinchuk** [terraform-aws-modules/terraform-aws-s3-bucket#131]
## Is your request related to a new offering from AWS?

It is supported by aws_s3_bucket_notification terraform resource (eventbridge = true/false).

## Is your request related to a problem? Please describe.

When you create a new S3 bucket sometimes it is required to enable EventBridge notifications for S3. 
In my case EventBridge triggers another AWS service that processes uploaded object, it can be done via CloudTrail, but it seems like enabling EventBridge directly is more convenient.

## Describe the solution you'd like.

It would be great to have an input variable, e.g. eventbridge = true/false that could be used to enable EventBridge notifications for current s3 bucket.

## Describe alternatives you've considered.

Alternatively we can use CloudTrail events, but it is much less convenient and seems more like legacy approach which was implemented by AWS before direct integration with EventBridge was released.

**Comment by antonbabenko** [comment]
Hi @igor-pinchuk !

Thanks for the proposal. You are welcome to open a PR if you have time.
