### ISSUE TITLE
Unit testing using localstack

### ISSUE THREAD

**Issue by ma-caylent** [terraform-aws-modules/terraform-aws-s3-bucket#132]
## Is your request related to a new feature? Please describe.

Hey! What about adding some unit testing? We can probably use safety terratest+localstack for common scenarios

Thanks

**Comment by antonbabenko** [comment]
Localstack != AWS. This is important unless users run production on localstack.

Terratest is not a solution I want us to have in these modules because it will require a lot of effort to maintain them. We have code in `examples` as a replacement to test (yes, it may sound weird but it is true).
