### ISSUE TITLE
Add source_account argument to lambda_permissions in s3_notification_module

### ISSUE THREAD

**Issue by AndriySidliarskiy** [terraform-aws-modules/terraform-aws-s3-bucket#134]
## Is your request related to a problem? Please describe.

When I enable security hub one I have one critical rule which have description - "You should ensure that access to the Lambda function is restricted to authorized principals only by using least privilege Lambda resource-based policies". Solve this problem it's  add this string to lambda permission, but in module you don't have an attribute [source_account] for lamba permissions.
{
 "StringEquals": {
  "AWS:SourceAccount": "[account_id]"
 },

## Describe the solution you'd like.

Add source_account attribute

**Comment by AlKapkone** [comment]
+1
Please, fix it asap, would be grateful!

**Comment by antonbabenko** [comment]
Good point. Pull request with added [`source_account`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission#source_account) is welcome. :)

**Comment by AlKapkone** [comment]
@antonbabenko Yep, sure. I'll do it immediately.

**Comment by AlKapkone** [comment]
@antonbabenko
```
git push origin source_account_lambda
ERROR: Permission to terraform-aws-modules/terraform-aws-s3-bucket.git denied to AlKapkone.
fatal: Could not read from remote repository.
```

**Comment by AlKapkone** [comment]
@antonbabenko Thanks, guru! For the quick response.
