### ISSUE TITLE
Version v0.1.0 removed from terraform registry

### ISSUE THREAD

**Issue by fliphess** [terraform-aws-modules/terraform-aws-s3-bucket#14]
Hi! 

Yesterday my pipeline crashed due to a deleted tag of this module in the terraform registry. 
We've fixed this by using a newer version, but to check if this is a common situation:

Does it happen more often that module tags of this and other `terraform-aws-modules` repositories are removed from the terraform registry?

**Comment by antonbabenko** [comment]
Hi @fliphess !

This is strange that module tag was removed from the terraform registry. `v0.1.0` was there since august and I have not been touching this tag since then.

Good that you updated to use a newer version, I am going to close this issue here.
