### ISSUE TITLE
Module upgrade from v2.x to v3.x causes lifecycle prefix to get eliminated

### ISSUE THREAD

**Issue by jhancock93** [terraform-aws-modules/terraform-aws-s3-bucket#158]
## Description

The lifecycle rule blocks used to support 
```
lifecycle_rule = [
    {
      id      = "Purge old logs"
      enabled = true
      prefix = "logs/"
      expiration = {
        days = 90
      }
      noncurrent_version_expiration = {
        days = 1
      }
    }]
```
Now ```prefix = "logs/"``` this must be implemented with:
```
filter = {
  prefix = "logs/"
}
```
As a result, lifecycle prefixes declared in the old way are ignored with the 3.x module upgrade. This is a dangerous change and needs to be called out on the page as this could cause data loss to users who are unaware. For example, a rule that deletes data from a logs folder after 90 days could suddenly be applied to the entire bucket.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v3.x

- Terraform version:

- Provider version(s):

## Reproduction Code [Required]

No

## Expected behavior

Some sort of documentation on module upgrade from v2.x to v3.x with a very clear warning should be on the main page. Even better would be something to detect the v2-style lifecycle prefix and throw an error.

## Actual behavior

Lifecycle prefixes declared in the old way are ignored causing potential data loss.

**Comment by cgstag** [comment]
I can confirm the above behaviour, which is a very dangerous change.
We actually nuked a bunch of our S3 buckets by accident with this change.

**Comment by zorji** [comment]
Thx, now I know why all my content are gone...

> Even better would be something to detect the v2-style lifecycle prefix and throw an error.

This will be nice

**Comment by antonbabenko** [comment]
Could you please open a PR updating the "Upgrade Migrations" section in [UPGRADE-3.0.md](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/UPGRADE-3.0.md#upgrade-migrations) where you add a section with details how it was in v2 and how it should be in v3? It would be very helpful for existing users.
