### ISSUE TITLE
Add aws_s3_bucket_public_access_block to this module

### ISSUE THREAD

**Issue by andrii29** [terraform-aws-modules/terraform-aws-s3-bucket#17]
Hello,
please add
https://www.terraform.io/docs/providers/aws/r/s3_bucket_public_access_block.html
resource to this module

Regards,
Andrii

**Comment by antonbabenko** [comment]
Hi @andrii29 ,

[v1.6.0](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/releases/v1.6.0) has been just released. It has support for blocking public access, see an example:

https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/0b4680a22110689b12cbc61cb016a5cad83feecc/examples/complete/main.tf#L178-L182

**Comment by andrii29** [comment]
Hello,

please add this values to outputs

Regards,
Andrii
