### ISSUE TITLE
Ability to use attribute source_hash in object module

### ISSUE THREAD

**Issue by Banjamino** [terraform-aws-modules/terraform-aws-s3-bucket#171]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Attribute etag is not compatible with KMS encryption, so I can`t use it during update of uploaded file via terraform. Need to use attribute source_hash instead etag, but this attribute is missing in current object module.
![image](https://user-images.githubusercontent.com/12988337/179393664-311a2134-5d2b-4955-aecb-cffdc03ee60e.png)

## Describe the solution you'd like.
Need to add attribute source_hash in object module.
![image](https://user-images.githubusercontent.com/12988337/179393785-75146cab-8a7f-432a-9408-90889e6997f1.png)

## Describe alternatives you've considered.
N/A

## Additional context
N/A

**Comment by SolidSly** [comment]
Commenting here to remove stale label.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.4.0 :tada:
