### ISSUE TITLE
Terraform version above 1.2.6 brakes module 

### ISSUE THREAD

**Issue by schrill** [terraform-aws-modules/terraform-aws-s3-bucket#173]
## Description

For some reason module syntax is no longer valid after upgrade to version 1.2.7, resulting in an error message on every argument that is not expected here.

`│ Error: Unsupported argument
│ 
│   on s3.tf line 8, in module "s3_bucket":
│    8:   bucket = var.bucket_full_name == "" ? "${var.project_env}.${local.bucket_name}" : var.bucket_full_name
│ 
│ An argument named "bucket" is not expected here.
`

**Comment by jeohist** [comment]
This is not a problem with the module: https://github.com/hashicorp/terraform/issues/31615

**Comment by schrill** [comment]
Figured that braking changes were probably introduced inside TF it self but since other modules were functioning correctly didn't do much investigation. Tnx for the link of the issue, pinned TF version to 1.2.6 for now...

**Comment by thomaskvnze** [comment]
We have similar issue. We use a module from the registry. Unfortunately, the module is downloaded, but the submodules used by that module are not, leading to half the module code not being there.

**Comment by antonbabenko** [comment]
The issue belongs to Terraform 1.2.7 - https://github.com/hashicorp/terraform/issues/31615.

Closing this issue here.
