### ISSUE TITLE
fix: Update deprecated parameter

### ISSUE THREAD

**Issue by zinheinyoma** [terraform-aws-modules/terraform-aws-s3-bucket#174]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: version = "~> 4.24.0"

## Is your request related to a problem? Please describe.

"NOTE on S3 Bucket Accelerate Configuration:
S3 Bucket Accelerate can be configured in either the standalone resource [aws_s3_bucket_accelerate_configuration](https://registry.terraform.io/providers/hashicorp/aws/s3_bucket_accelerate_configuration) or with the deprecated parameter acceleration_status in the resource aws_s3_bucket. Configuring with both will cause inconsistencies and may overwrite configuration."

## Describe the solution you'd like.

Update Parameters in module.

**Comment by spicysomtam** [comment]
While you are at it, can you fix the lifecycle deprecated setting, causing this:
```
Warning: Deprecated attribute
│ 
│   on .terraform/modules/s3_mybucket/main.tf line 27, in resource "aws_s3_bucket" "this":
│   27:       acceleration_status,
│ 
│ The attribute "acceleration_status" is deprecated. Refer to the provider
│ documentation for details.
│ 
│ (and 5 more similar warnings elsewhere)
```

**Comment by SupSkiFun** [comment]
Also deprecated **acl** and **request_payer** seem to be affected.  
Commenting out lines 27, 28 and 35 in main.tf squelched all errors for me.

  lifecycle {
    ignore_changes = [
      **# acceleration_status,
      # acl,**
      grant,
      cors_rule,
      lifecycle_rule,
      logging,
      object_lock_configuration,
      replication_configuration,
      **# request_payer,**
      server_side_encryption_configuration,
      versioning,
      website
    ]

 Warning: Deprecated attribute
│
│   on .terraform\modules\s3-bucket\main.tf line 28, in resource "aws_s3_bucket" "this":
│   28:       acl,
│
│ The attribute "acl" is deprecated. Refer to the provider documentation for details.
│
│ (and one more similar warning elsewhere)

│ Warning: Deprecated attribute
│
│   on .terraform\modules\s3-bucket\main.tf line 35, in resource "aws_s3_bucket" "this":
│   35:       request_payer,
│
│ The attribute "request_payer" is deprecated. Refer to the provider documentation for details.
