### ISSUE TITLE
Need to update some deprecated terraform variables parameter in modules

### ISSUE THREAD

**Issue by heinhtetnwyoma** [terraform-aws-modules/terraform-aws-s3-bucket#175]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

## Reproduction Code [Required]

Refer to this terraform doc : https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket

We need to update modules with latest terraform resources.

## Expected behavior

This module is not occurred the deprecated status.

## Actual behavior

```
Warning: Deprecated attribute
│   on .terraform/modules/s3-storage/main.tf line 27, in resource "aws_s3_bucket" "this":
│   27:       acceleration_status,
│ 
│ The attribute "acceleration_status" is deprecated. Refer to the provider
│ documentation for details.
│ 
│ (and 4 more similar warnings elsewhere)
```

![image](https://user-images.githubusercontent.com/104350766/184581336-a0a3d273-c42d-4048-a442-83d147f10026.png)

### Terminal Output Screenshot(s)

![image](https://user-images.githubusercontent.com/104350766/184581315-1d22901f-df2c-444b-903b-297f7be78bd7.png)

**Comment by FarhanShoukat** [comment]
Facing the same issue

**Comment by antonbabenko** [comment]
It would REALLY HELP if you complete the issue template and provide all required details (code snippets, versions, etc).
