### ISSUE TITLE
Ability to apply examples without errors

### ISSUE THREAD

**Issue by SolidSly** [terraform-aws-modules/terraform-aws-s3-bucket#177]
## Description

Currently, it is not possible to apply the `complete` example.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: `v3.3.0`

- Terraform version: `Terraform v1.2.7`

- Provider version(s): `aws v4.27.0` / `random v3.3.2`

## Reproduction Code [Required]

```
cd examples/complete

export AWS_REGION=us-east-1
export AWS_PROFILE=XXX

terraform init
terraform apply
```

## Expected behavior

The user can apply the exemple folders without any errors.

## Actual behavior

```
╷
│ Error: error creating S3 bucket ACL for cloudfront-logs-prime-phoenix: AccessDenied: Access Denied
│ 	status code: 403, request id: JGQSG58NXGD2YWQY, host id: m6WVzathZqHGRRky1vD297gbQPIrX8NF2+mZ9J7nsFvDeg+l4cSW8DO6DG1+LzeM/cbO0HYM0lE=
│
│   with module.cloudfront_log_bucket.aws_s3_bucket_acl.this[0],
│   on ../../main.tf line 35, in resource "aws_s3_bucket_acl" "this":
│   35: resource "aws_s3_bucket_acl" "this" {
│
╵
```

**Comment by antonbabenko** [comment]
`AccessDenied: Access Denied` - Do you have sufficient permissions to do what you need? Could you try with Admin permissions?

I have run these examples many times before, and a similar example yesterday.

**Comment by SolidSly** [comment]
Thank you for your time.
I have `AdministratorAccess` access on the account.

If I comment the grant part in the example and that I add the ACL with the "log-delivery-write" value, then, the apply can be done. 🤔 

```
module "cloudfront_log_bucket" {
  source = "../../"

  bucket    = "cloudfront-logs-${random_pet.this.id}"
  acl       = "log-delivery-write"

#  grant = [{
#    type       = "CanonicalUser"
#    permission = "FULL_CONTROL"
#    id         = data.aws_canonical_user_id.current.id
#    }, {
#    type       = "CanonicalUser"
#    permission = "FULL_CONTROL"
#    id         = data.aws_cloudfront_log_delivery_canonical_user_id.cloudfront.id # Ref. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html
#    }
#  ]

  owner = {
    id = "457414f555e45c2e6fe1069d1a527a90d6337e1acb012ba99f3833859b23d338"
  }

  force_destroy = true
}
```

I also encounter issues on the `object` example ❌ :
```
╷
│ Error: Error uploading object to S3 bucket (concise-chamois-with-object-lock): InvalidRequest: Bucket is missing ObjectLockConfiguration
│ 	status code: 400, request id: 38CFBZCBYNNFKN9B, host id: qEu6X525qSDMGAZvgeKs7OvtKO7E34nrYk6Z/NON1pEwqU7/s57jKs4Ubx/wKBuJrLK2xGXCflc=
│
│   with module.object_locked.aws_s3_object.this[0],
│   on ../../modules/object/main.tf line 1, in resource "aws_s3_object" "this":
│    1: resource "aws_s3_object" "this" {
│
╵
```

I don't have any errors with the  `s3-replication` example ✅ 
I don't have any errors with the  `notification` example ✅ 
I don't have any errors with the  `complete-legacy` example ✅
