### ISSUE TITLE
Reading the source of this module I have a question about a terraform construct I can't find documentation for

### ISSUE THREAD

**Issue by rcousens** [terraform-aws-modules/terraform-aws-s3-bucket#194]
https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/main.tf#L309

Can anyone point me to documentation for terraform that explains this `and {` block construct in a dynamic content block?

**Comment by antonbabenko** [comment]
https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks

`and` is just the name of the block within the `filter` block.

Please ask generic questions like this at https://discuss.hashicorp.com
