### ISSUE TITLE
unable to use lifecycle meta argument prevent_destroy

### ISSUE THREAD

**Issue by shettypriy** [terraform-aws-modules/terraform-aws-s3-bucket#203]
I am trying to refractor the terraform resource to module and currently unable to use the following lifecyle meta-arguments 

lifecycle {
    prevent_destroy = "true"
  }

It gives me the following error 

Error: Reserved block type name in module block
The block type name "lifecycle" is reserved for use by Terraform in a future version.

Ref issue https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/186

**Comment by antonbabenko** [comment]
Terraform doesn't allow the use of variables inside of lifecycle blocks and we can't pass `lifecycle` into the module.
