### ISSUE TITLE
unable to use the aws_s3_bucket_notification in the aws s3 module

### ISSUE THREAD

**Issue by shettypriy** [terraform-aws-modules/terraform-aws-s3-bucket#206]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is available in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
I am trying to convert the resource "aws_s3_bucket_notification"  to a module using the "terraform-aws-modules/s3-bucket/aws" , Therefore, I used the below code to replace the resource "aws_s3_bucket_notification" to a module. I tried to use the github link for the source path as shown below

module "test_bucket_notification" {
 source = "git::https://github.com/terraform-aws-modules/terraform-aws-s3-bucket.git//modules/notification"
 bucket = module.test_bucket.s3_bucket_id
 sqs_notifications = {
 test_bucket_sqs = {
   queue_arn     = module.test_queue.sqs_queue_arn
   events        = ["s3:ObjectCreated:*"]
   filter_prefix = “test”
 }
}
}
## Describe the solution you'd like.
Is there anyway to use the s3 bucket notification without using the github link as shown above. I would like to use the source for s3 notification similar to "terraform-aws-modules/s3-bucket/aws//modules/notification"

## Describe alternatives you've considered.
module "test_bucket_notification" {
 source = "git::https://github.com/terraform-aws-modules/terraform-aws-s3-bucket.git//modules/notification"
 bucket = module.test_bucket.s3_bucket_id
 sqs_notifications = {
 test_bucket_sqs = {
   queue_arn     = module.test_queue.sqs_queue_arn
   events        = ["s3:ObjectCreated:*"]
   filter_prefix = “test”
 }
}
}

**Comment by antonbabenko** [comment]
Please check this out - https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories

And ask generic Terraform questions on https://discuss.hashicorp.com
