### ISSUE TITLE
acceleration_status deprecated

### ISSUE THREAD

**Issue by arunr7787** [terraform-aws-modules/terraform-aws-s3-bucket#211]
## Description

acceleration_status is deprecated. Hence when we try to use this module we get the following error, 

Error:
The attribute "acceleration_status" is deprecated. Refer to the provider documentation for details.

Could you please fix the same or let me know if there is any workaround ?

**Comment by antonbabenko** [comment]
If this is an issue, please fill in the issue template. I don't see this issue myself.
