### ISSUE TITLE
Remote state error after removing module

### ISSUE THREAD

**Issue by BenSlabbert** [terraform-aws-modules/terraform-aws-s3-bucket#22]
Hello,

I have removed the s3_bucket module from my code, however after running apply I get the error:

Error: leftover module module.s3_bucket in state that should have been removed; this is a bug in Terraform and should be reported

Terraform v0.12.19
Module version: 1.5.0

**Comment by shanedroid** [comment]
@BenSlabbert see https://github.com/hashicorp/terraform/issues/22579#issuecomment-595355172 may be related, you may be able to resolve this manually by modifying your statefile or updating TF version 🤞

**Comment by bryantbiggs** [comment]
closing since this is an upstream issue
