### ISSUE TITLE
`bucket` values are `known after apply`

### ISSUE THREAD

**Issue by brittandeyoung** [terraform-aws-modules/terraform-aws-s3-bucket#259]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

The `aws_s3_bucket_acl`, `aws_s3_bucket_public_access_block`, and `aws_s3_bucket_server_side_encryption_configuration` resources have `bucket` value that is `known after apply`. This causes problems when using IaC code scanning tools to scan your plan output as these tools use this field in order to make sure that the bucket does indeed have and `acl` and `public_access_block` configured. 

## Versions

- Module version [Required]: 3.15.1

- Terraform version: 1.6.3
- Provider version(s): 4.67.0 aws

## Reproduction Code [Required]

You can reproduce this issue using any of the example configurations. 

Use any of the example configurations to:
```shell
terraform init
terraform plan 
```

Look at the plan values for the `aws_s3_bucket_acl` and `aws_s3_bucket_public_access_block` resources. They will show a value of `known after apply`

example:
```
  # module.da_s3_files_bucket.aws_s3_bucket_acl.this[0] will be created
  + resource "aws_s3_bucket_acl" "this" {
      + acl    = "private"
      + bucket = (known after apply)
      + id     = (known after apply)

      + access_control_policy {
          + grant {
              + permission = (known after apply)

              + grantee {
                  + display_name  = (known after apply)
                  + email_address = (known after apply)
                  + id            = (known after apply)
                  + type          = (known after apply)
                  + uri           = (known after apply)
                }
            }

          + owner {
              + display_name = (known after apply)
              + id           = (known after apply)
            }
        }
    }

  # module.da_s3_files_bucket.aws_s3_bucket_public_access_block.this[0] will be created
  + resource "aws_s3_bucket_public_access_block" "this" {
      + block_public_acls       = false
      + block_public_policy     = false
      + bucket                  = (known after apply)
      + id                      = (known after apply)
      + ignore_public_acls      = false
      + restrict_public_buckets = false
    }



```

## Expected behavior

The `bucket` value for the `aws_s3_bucket_acl`, `aws_s3_bucket_public_access_block`, and `aws_s3_bucket_server_side_encryption_configuration`  resources should be known as that is a required value when creating a bucket.

## Actual behavior

The `bucket` value for the `aws_s3_bucket_acl`, `aws_s3_bucket_public_access_block`, and `aws_s3_bucket_server_side_encryption_configuration` is `(known after apply)`

## Additional context

This really matters when running IaC Scans against your plan output. Without the `bucket` value having a known value, common security tests will fail. 

/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/30ec69f3-af5e-4507-872f-1c927fde15c8.sh
WARN - /home/vsts/work/_temp/tfplan.json - main - TFP004: S3 bucket has no access blocks ( https://dev.azure.com/hagerty/Hagerty/_wiki/wikis/hagerty.wiki/24087/TFP004-Buckets-Without-Access-Blocks ): module.da_s3_files_bucket.aws_s3_bucket.this[0]
FAIL - /home/vsts/work/_temp/tfplan.json - main - TFP003: S3 bucket is missing private acl ( https://dev.azure.com/hagerty/Hagerty/_wiki/wikis/hagerty.wiki/24083/TFP003-Buckets-Without-Private-ACL ): module.da_s3_files_bucket.aws_s3_bucket.this[0]
FAIL - /home/vsts/work/_temp/tfplan.json - main - TFP005: S3 bucket is not encrypted, see document ( https://dev.azure.com/hagerty/Hagerty/_wiki/wikis/hagerty.wiki/25179/TFP005-S3-Bucket-is-not-encrypted ): module.da_s3_files_bucket.aws_s3_bucket.this[0]

**Comment by brittandeyoung** [comment]
This is still an active issue.

**Comment by brittandeyoung** [comment]
This is still an active issue. Is this module still maintained?

**Comment by antonbabenko** [comment]
This module is maintained. What you describe is the expected behavior, and I don't think we will fix it the way you propose.

`id` is used because we need to respect all the dependencies instead of just reporting the static value (via the `bucket` attribute).

We can't use the `bucket` attribute reliable because users can use `bucket_prefix` - this means we will get the full bucket name from AWS (`known after apply`).

**Comment by brittandeyoung** [comment]
@antonbabenko I agree with you that we cannot use the `bucket` attribute when a `bucket_prefix` is provided and designed my PR with that in mind. 

I used the [coalesce](https://developer.hashicorp.com/terraform/language/functions/coalesce) function to use the first non `null` value between `bucket` and `id` like so `coalesce(aws_s3_bucket.this[0].bucket, aws_s3_bucket.this[0].id)` . This will then use the `bucket` value when it is provided and the `id` value when it is not provided. 

Would you mind taking a second pass at this?

**Comment by antonbabenko** [comment]
Using `coalesce` with `bucket` and `id` attributes may look like it works for your case (rather peculiar and not very common case), but it doesn't consider `bucket_prefix` correctly. This means that we can't have partial support for this in the module.

**Comment by brittandeyoung** [comment]
@antonbabenko would you entertain reviewing the pr if I were to use a conditional so that `bucket` is only used when the `bucket_prefix` is `null`?

**Comment by antonbabenko** [comment]
I don't think that supporting such a use-case when `bucket` is provided makes a lot of sense to be implemented in this module.

**Comment by brittandeyoung** [comment]
Thank you for your responses. I will let this issue die =)
