### ISSUE TITLE
Breaking change introduced in 4.2.0

### ISSUE THREAD

**Issue by BeyondEvil** [terraform-aws-modules/terraform-aws-s3-bucket#291]
This [change](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/commit/f6fda8c746d2b6951ae59d7a20d33dbaafe0d70f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L135) causes `Error: Failed to query available provider packages` given this version pin:

```hcl
module "private_s3" {
  source  = "terraform-aws-modules/s3-bucket/aws"
  version = "~> 4.0"
  ...
```

given the following AWS provider config:

```hcl
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.65.0"
    }
    ...
```

No action here I guess, but wanted to share if someone else gets this as the output from terraform isn't very helpful.

**Comment by antonbabenko** [comment]
Module version 4.2.0 requires at least version 5.70.0 of AWS provider. Please make sure that you run `terraform init -upgrade` to fetch newer version of the providers.

**Comment by BeyondEvil** [comment]
> Module version 4.2.0 requires at least version 5.70.0 of AWS provider. Please make sure that you run `terraform init -upgrade` to fetch newer version of the providers.

For some reason that failed with the same error.

Regardless, this isn't necessarily a terraform-aws-modules fault.

When using 3rd-party modules, one should pin the exact version as per best practices:
https://developer.hashicorp.com/terraform/language/expressions/version-constraints#best-practices
