### ISSUE TITLE
Same bucket policy to multiple buckets (different RESOURCE)

### ISSUE THREAD

**Issue by kereza** [terraform-aws-modules/terraform-aws-s3-bucket#32]
Hello and that you very much for this nice module.

After losing quite some time of figuring our how to attach the same bucket policy to multiple buckets (using ONE policy document) I decided to ask here. So is there any "nice way" to attache the same bucket policy to multiple buckets created with this module. Lets say I created two buckets with the module (Can I use ONE module statement to create 2 or more buckets ? ). At the moment I am creating the buckets like this:

```
module "s3-1" {`
     source = ".../"
     bucket = "test1"
     policy        = data.aws_iam_policy_document.test.json
}

 module "s3-2" {
     source = ".../"
     bucket = "test2"
     policy        = data.aws_iam_policy_document.test.json
}

data "aws_iam_policy_document" "test" {
   statement {

        sid = "DenyIncorrectEncryptionHeader"
        effect = "Deny"
        principals {
            type = "AWS"
            identifiers = ["*"]
        }
        actions = ["s3:PutObject"]
        resources = [
             "${module.s3-1.this_s3_bucket_arn}/*"
        ]
        condition {
            test = "StringNotEquals"
            variable = "s3:x-amz-server-side-encryption"
            values = ["AES256"]
        }
    }
}
```

So I want to do something like this, the problem that i have is that in the POLICY in the RESOURCE section I want/need to have ONLY the bucket ARN of the current bucket.  I know I can create multiple policy documents and use it for the different buckets, but is there a better way to do this. I was searching between dynamic_blocks, for_each, count etc. But nothing worked for me.

Any help is appreciated  :)

**Comment by bryantbiggs** [comment]
I think the best route would be to create once policy outside of this module and then pass it in to each S3 bucket configuration created using this module
