### ISSUE TITLE
Can't set region other than profile region

### ISSUE THREAD

**Issue by gvashchenkolineate** [terraform-aws-modules/terraform-aws-s3-bucket#37]
Hi everyone!

I can't identify whether problem is on my side or it's an issue in the module.
I'm using the module as a part of my own module
and I'm creating a couple of buckets and all of them get `us-west-2` region despite what I'm passing as `region` var.

Code in my module `./modules/repo/main.tf`:
```
module "s3-bucket" {
  source  = "terraform-aws-modules/s3-bucket/aws"
  version = "1.9.0"
  region = var.bucket-region

  bucket               = "${local.pfx}-${var.bucket-name}-${var.env}"
  acl                  = "private"
  attach_public_policy = false

  versioning = {
    enabled = true
  }

  tags = local.tags
}
```

Main code `./main.tf` :
```
module "repo-dev" {
  source = "./modules/repo"
  bucket-region = "us-west-2"   // <---------- that's created as expected
  env    = "dev"
}

module "repo-production" {
  source = "./modules/repo"
  bucket-region = "us-east-1"   // <---------- that's dropped to 'us-west-2'
  env    = "production"
}
```

`terraform plan` reportings are fine, but after `terraform apply` both buckets have region `us-west-2`.

It must be said that I'm using `us-west-2` as an AWS provider setting:
```
provider "aws" {
  version = "~> 2.35"
  profile = var.profile
  region  = "us-west-2"
}
```
But [the docs](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/v1.9.0/README.md) says that bucket region will override profile region:
> region   (Optional) If specified, the AWS region this bucket should reside in. Otherwise, the region used by the callee.

Could you please point me out what I'm doing wrong?

Thanks!

**Comment by moosamus** [comment]
I just ran into this issue, and it appears that this was changed upstream to a read-only attribute: https://github.com/terraform-providers/terraform-provider-aws/pull/14127

I believe it can now only use the profile region as you indicated.

**Comment by gvashchenkolineate** [comment]
Oh, thanks!

So using different providers for each region can be a solution
like posted by @endofcake in https://github.com/terraform-providers/terraform-provider-aws/issues/1656#issuecomment-331324669
