### ISSUE TITLE
No versioning breaks runs

### ISSUE THREAD

**Issue by semperfitodd** [terraform-aws-modules/terraform-aws-s3-bucket#41]
├── provider.aws
├── module.access
│   ├── provider.aws (inherited)
│   ├── module.jenkins
│   │   ├── provider.aws (inherited)
│   │   └── provider.random
│   ├── module.jenkins-alb
│   │   ├── provider.aws (inherited)
│   │   ├── module.alb
│   │       └── provider.aws ~> 2.54
│   │   ├── module.alb_4xx_errors
│   │       └── provider.aws (inherited)
│   │   ├── module.alb_request_count
│   │       └── provider.aws (inherited)
│   │   └── module.alb_response_time
│   │       └── provider.aws (inherited)
│   ├── module.key
│   │   ├── provider.aws (inherited)
│   │   └── provider.tls
│   ├── module.openvpn
│   │   ├── provider.acme
│   │   ├── provider.aws (inherited)
│   │   ├── provider.null
│   │   ├── provider.random
│   │   ├── provider.tls
│   │   ├── module.openvpn_cpu
│   │       └── provider.aws (inherited)
│   │   └── module.openvpn_status
│   │       └── provider.aws (inherited)
│   └── module.vpc
│       └── provider.aws >= 2.57, < 4.0
├── module.config_global
│   ├── provider.aws (inherited)
│   ├── provider.random
│   └── module.config_bucket
│       └── provider.aws >= 3.0, < 4.0
├── module.config_regional
│   └── provider.aws (inherited)
├── module.dev
│   ├── provider.aws (inherited)
│   ├── module.key
│       ├── provider.aws (inherited)
│       └── provider.tls
│   ├── module.rds
│       ├── provider.aws (inherited)
│       ├── provider.random
│       └── module.this
│           ├── provider.aws >= 2.49, < 4.0
│           ├── module.db_instance
│               └── provider.aws (inherited)
│           ├── module.db_option_group
│               └── provider.aws (inherited)
│           ├── module.db_parameter_group
│               └── provider.aws (inherited)
│           └── module.db_subnet_group
│               └── provider.aws (inherited)
│   ├── module.redis
│       └── provider.aws (inherited)
│   ├── module.test-alb
│       ├── provider.aws (inherited)
│       ├── module.alb
│           └── provider.aws ~> 2.54
│       ├── module.alb_4xx_errors
│           └── provider.aws (inherited)
│       ├── module.alb_request_count
│           └── provider.aws (inherited)
│       └── module.alb_response_time
│           └── provider.aws (inherited)
│   ├── module.test-instance
│       ├── provider.aws (inherited)
│       └── module.cloudwatch_asg_cpu
│           └── provider.aws (inherited)
│   ├── module.vpc
│       └── provider.aws >= 2.57, < 4.0
│   ├── module.web-alb
│       ├── provider.aws (inherited)
│       ├── module.alb
│           └── provider.aws ~> 2.54
│       ├── module.alb_4xx_errors
│           └── provider.aws (inherited)
│       ├── module.alb_request_count
│           └── provider.aws (inherited)
│       └── module.alb_response_time
│           └── provider.aws (inherited)
│   └── module.web-instance
│       ├── provider.aws (inherited)
│       └── module.cloudwatch_asg_cpu
│           └── provider.aws (inherited)
├── module.global_infra
│   ├── provider.aws (inherited)
│   ├── module.administrator_group
│       └── provider.aws >= 2.23, < 4.0
│   ├── module.backup
│       └── provider.aws (inherited)
│   ├── module.billing_group
│       └── provider.aws >= 2.23, < 4.0
│   ├── module.cloudtrail
│       ├── provider.archive
│       ├── provider.aws (inherited)
│       ├── provider.template
│       ├── module.cloudtrail
│           └── provider.aws >= 3.0, < 4.0
│       ├── module.root_user_metric_alarm
│           └── provider.aws (inherited)
│       └── module.root_user_metric_filter
│           └── provider.aws (inherited)
│   ├── module.formpiper-env
│       └── provider.aws >= 3.0, < 4.0
│   └── module.read_only_group
│       └── provider.aws >= 2.23, < 4.0
├── module.guardduty_global
│   ├── provider.aws (inherited)
│   └── module.config_bucket
│       └── provider.aws >= 3.0, < 4.0
├── module.guardduty_regional
│   └── provider.aws (inherited)
├── module.prod
│   ├── provider.aws (inherited)
│   ├── module.key
│       ├── provider.aws (inherited)
│       └── provider.tls
│   ├── module.rds
│       ├── provider.aws (inherited)
│       ├── provider.random
│       └── module.this
│           ├── provider.aws >= 2.49, < 4.0
│           ├── module.db_instance
│               └── provider.aws (inherited)
│           ├── module.db_option_group
│               └── provider.aws (inherited)
│           ├── module.db_parameter_group
│               └── provider.aws (inherited)
│           └── module.db_subnet_group
│               └── provider.aws (inherited)
│   ├── module.redis
│       └── provider.aws (inherited)
│   ├── module.vpc
│       └── provider.aws >= 2.57, < 4.0
│   ├── module.web-alb
│       ├── provider.aws (inherited)
│       ├── module.alb
│           └── provider.aws ~> 2.54
│       ├── module.alb_4xx_errors
│           └── provider.aws (inherited)
│       ├── module.alb_request_count
│           └── provider.aws (inherited)
│       └── module.alb_response_time
│           └── provider.aws (inherited)
│   └── module.web-instance
│       ├── provider.aws (inherited)
│       └── module.cloudwatch_asg_cpu
│           └── provider.aws (inherited)
├── module.regional_infra
│   ├── provider.aws (inherited)
│   ├── module.cloudwatch_sns
│       ├── provider.aws (inherited)
│       └── provider.template
│   └── module.ssm
│       └── provider.aws (inherited)
├── module.security_hub
│   └── provider.aws (inherited)
├── module.stage
│   ├── provider.aws (inherited)
│   ├── module.key
│       ├── provider.aws (inherited)
│       └── provider.tls
│   ├── module.rds
│       ├── provider.aws (inherited)
│       ├── provider.random
│       └── module.this
│           ├── provider.aws >= 2.49, < 4.0
│           ├── module.db_instance
│               └── provider.aws (inherited)
│           ├── module.db_option_group
│               └── provider.aws (inherited)
│           ├── module.db_parameter_group
│               └── provider.aws (inherited)
│           └── module.db_subnet_group
│               └── provider.aws (inherited)
│   ├── module.redis
│       └── provider.aws (inherited)
│   ├── module.vpc
│       └── provider.aws >= 2.57, < 4.0
│   ├── module.web-alb
│       ├── provider.aws (inherited)
│       ├── module.alb
│           └── provider.aws ~> 2.54
│       ├── module.alb_4xx_errors
│           └── provider.aws (inherited)
│       ├── module.alb_request_count
│           └── provider.aws (inherited)
│       └── module.alb_response_time
│           └── provider.aws (inherited)
│   └── module.web-instance
│       ├── provider.aws (inherited)
│       └── module.cloudwatch_asg_cpu
│           └── provider.aws (inherited)
└── module.tgw
    └── provider.aws (inherited)

The S3 module now requires AWS provider 3.0 or higher. Many other modules aren't ready for 3.0. Since a version suitable for AWS ~2.0, the is breaking when running terraform init. Please allow for a fix for this.

**Comment by antonbabenko** [comment]
I see that ALB module you are using is not compatible with AWS provider version 3.

If you are using [https://github.com/terraform-aws-modules/terraform-aws-alb](https://github.com/terraform-aws-modules/terraform-aws-alb) then you can update version to [v5.7.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.7.0) which has been just released with the support for AWS provider version 3 and Terraform 0.13.

I am planning to finish updates of all modules during today and tomorrow. Most of them are already done.

Please let me know if there are other `terraform-aws-modules` that are blocking you.

**Comment by antonbabenko** [comment]
Closing this issue, because the largest part of module in terraform-aws-modules are now compatible with AWS provider version 3 and Terraform 0.13.
