### ISSUE TITLE
Feature-Request Replication Configuration after Bucket Creation

### ISSUE THREAD

**Issue by smeluski** [terraform-aws-modules/terraform-aws-s3-bucket#42]
Feature Request: replication_configuration after bucket creation

Scenario: Allow creation of replication_configuration outside of bucket creation. In order to create bi-directional replication both buckets need to exist before replication can be configured. I do not believe there is currently a way to support this scenario. 

Potential Solution: Separate out the replication configuration so it can be applied to the bucket after creation, similar to bucket policy.

**Comment by bryantbiggs** [comment]
I don't believe bi-directional replication is supported in AWS and in any case, I don't know if adding replication here makes a lot of sense because it requires at least two buckets. we could maybe add the replication "glue" (role, config, etc.) into a separate sub-module within the project as a middle ground. we'll see

**Comment by tcharewicz** [comment]
It's possible, and its works. Currently I make it with null resources. Example below.

resource "null_resource" "s3_bucket_replication" {
  count = local.enable_kms * var.enable_aws_sync

  triggers = {
    template_rendered = data.template_file.s3_bucket_replication[0].rendered
  }

  provisioner "local-exec" {
    command = <<CMD
    ${local.role_assume_cmd} \
    aws s3api put-bucket-replication --bucket ${local.s3_bucket_name} --replication-configuration file://s3_bucket_replication.json
CMD

  }

  depends_on = [
    local_file.s3_bucket_replication,
    aws_s3_bucket.s3_bucket,
    aws_s3_bucket.s3_bucket_dest,
  ]
}

resource "null_resource" "s3_bucket_dest_replication" {
  count = local.enable_kms * var.enable_aws_sync

  triggers = {
    template_rendered = data.template_file.s3_bucket_dest_replication[0].rendered
  }

  provisioner "local-exec" {
    command = <<CMD
    ${local.role_assume_cmd} \
    aws s3api put-bucket-replication --bucket ${local.s3_bucket_dst_name} --replication-configuration file://s3_bucket_dest_replication.json
CMD

  }

  depends_on = [
    local_file.s3_bucket_replication,
    aws_s3_bucket.s3_bucket,
    aws_s3_bucket.s3_bucket_dest,
  ]
}

**Comment by antonbabenko** [comment]
Instead of using AWS CLI and `null_resource`, why can't you pass the replication configuration into `replication_configuration` argument in the module and create required IAM resources outside of the module?

The trick here is to compose ARN of the buckets before calling this module to create them to be able to create IAM role and pass it to `replication_configuration`.

**Comment by tcharewicz** [comment]
@smeluski wants to create bi-directional bucket replication and in TF there is no additional resource to setup that. That's why I use null resources and aws cli.

**Comment by nckbnv** [comment]
> Instead of using AWS CLI and `null_resource`, why can't you pass the replication configuration into `replication_configuration` argument in the module and create required IAM resources outside of the module?
> 

It doesn't work for bi-directional CRR as it enters a cycle loop as per [upstream #749](https://github.com/terraform-providers/terraform-provider-aws/issues/749)

> The trick here is to compose ARN of the buckets before calling this module to create them to be able to create IAM role and pass it to `replication_configuration`.

Even with the ARN trick it doesn't work completely for bi-directional replication if you create the two buckets simultaneously as described [in one of the comments in the issue linked above](https://github.com/terraform-providers/terraform-provider-aws/issues/749#issuecomment-460801778), especially if you also have custom KMS keys in play as well. It could potentially work at some point in time, as it will create at least one of the buckets, but it far from optimal. 

The only option to handle it is basically to pre-create the buckets first and then add the replication configuration on a sub-sequent run, but that's sub-optimal too.

The other option is to use null_resource as suggested by @tcharewicz. 

However, I hit an issue with that too. If you use the module to create the bucket and then add the replication configuration with a null_resource, upon subsequent terraform apply the replication_configuration is going to be overwritten as described in [upstream #665](https://github.com/terraform-providers/terraform-provider-aws/issues/665). 
@tcharewicz have you observed anything like that in your case?

Either way, imho, there is no proper way to handle the cycle loop in the module itself up until terraform fix this one upstream.

**Comment by tcharewicz** [comment]
>@tcharewicz have you observed anything like that in your case?

In bucket replication I only have one rule and my configuration looks like this (below) and I have no problems with the replication configuration.

{
    "Role": "${replication_role}",
    "Rules": [
        {
            "ID": "${replication_name}",
            "Status": "Enabled",
            "Priority": 1,
            "DeleteMarkerReplication": {
                "Status": "Disabled"
            },
            "Filter": {},
            "Destination": {
                "Bucket": "${dest_bucket_arn}"
            }
        }
    ]
}
