### ISSUE TITLE
Grants have issue.

### ISSUE THREAD

**Issue by hirenshah005** [terraform-aws-modules/terraform-aws-s3-bucket#45]
Hi @antonbabenko while using Grants like this as per example 
```
  grant = [{
    type        = "CanonicalUser"
    permissions = ["FULL_CONTROL"]
    id          = data.aws_canonical_user_id.current.id
  }, {
    type        = "Group"
    permissions = ["READ_ACP", "WRITE"]
    uri          = "http://acs.amazonaws.com/groups/s3/LogDelivery"
  }]


```
I am getting below error
```
  12:   grant = [{
  13:     type        = "CanonicalUser"
  14:     permissions = ["FULL_CONTROL"]
  15:     id          = data.aws_canonical_user_id.current.id
  16:   }, {
  17:     type        = "Group"
  18:     permissions = ["READ_ACP", "WRITE"]
  19:     uri          = "http://acs.amazonaws.com/groups/s3/LogDelivery"
  20:   }]
```

The given value is not suitable for child module variable "grant" defined at
.terraform/modules/s3.example-infrastructure/variables.tf:97,1-17: all list
elements must have the same type.

**Comment by hirenshah005** [comment]
@antonbabenko in my opinion the grant variable should be set to any.
```
variable "grant" {
  description = "An ACL policy grant. Conflicts with `acl`"
  type        = any
  default     = []
} 
```
As this worked in my case.

**Comment by antonbabenko** [comment]
Hi!

You are absolutely right.

Please update to use [v1.14.0](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/releases/v1.14.0) which has been just released.
