### ISSUE TITLE
Issue with S3 Grants

### ISSUE THREAD

**Issue by hirenshah005** [terraform-aws-modules/terraform-aws-s3-bucket#47]
Hi @antonbabenko everytime I run plan the grants show up as change that needs to be applied though it was applied before. Any idea what's breaking here?
```
      + grant {
          + permissions = [
              + "READ_ACP",
              + "WRITE",
            ]
          + type        = "Group"
          + uri         = "http://acs.amazonaws.com/groups/s3/LogDelivery"
        }
      + grant {
          + id          = "canonical-id"
          + permissions = [
              + "FULL_CONTROL",
            ]
          + type        = "CanonicalUser"
        }
```

**Comment by antonbabenko** [comment]
No ideas, sorry. Maybe there is an open issue in Terraform AWS provider?

**Comment by hirenshah005** [comment]
Thanks I see one https://github.com/terraform-providers/terraform-provider-aws/issues/13109

**Comment by bryantbiggs** [comment]
closing since this is an upstream issue with the provider
