### ISSUE TITLE
terraform validate:  -- Error: Computed attribute cannot be set

### ISSUE THREAD

**Issue by atrakic** [terraform-aws-modules/terraform-aws-s3-bucket#52]
I'm experiencing error when trying import this module. According to this thread  var.region is depricated:
https://discuss.hashicorp.com/t/computed-attribute-cannot-be-set-for-aws-s3-bucket-region/13309/3

My setup:
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.8.0

**Comment by antonbabenko** [comment]
This has been already fixed, see https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/38 .

If you still have issues with `region`, make sure to update the version of this module.
