### ISSUE TITLE
Feature request: allow non-AWS S3 endpoints

### ISSUE THREAD

**Issue by synergiator** [terraform-aws-modules/terraform-aws-s3-bucket#56]
In the meantime, AWS S3 interface has been implemented also by other vendors.

That is, an S3 integration should not hardcode the service endpoint.

As it seems from the parametrization specs in the documentation, there is no possibility to use a custom endpoint.

If so, please implement this feature.

**Comment by antonbabenko** [comment]
Hi,

You should instruct AWS provider to use custom endpoints as described here - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints

There is nothing we can or should do in the module (unless I miss the point).

**Comment by synergiator** [comment]
Hi there @antonbabenko thanks for the rapid reaction!
Sorry if I'm mixing things up but I've understood:

* I can use different *providers*, also AWS, and configure custom endpoints as you've explained
* I can specify *backends* for state files, also S3, and I can create an S3 bucket dynamically using your plugin "terraform-aws-s3-bucket"

Correct?

Then as it seems, while using terraform-aws-s3-bucket, I can't tell it to create the bucket for the state file using custom endpoint (independent of further provider configuration), or do I?

**Comment by antonbabenko** [comment]
Correct. When you call the module you can pass provider's configuration you want to use there (see [this](https://www.terraform.io/docs/configuration/providers.html#selecting-alternate-provider-configurations)). This way you can have several AWS providers blocks in your code and define which one to pass to a module.

Keep in mind, that it is better to manage state buckets outside of your normal configurations to avoid the chicken-and-egg problem.

Hope I answered your questions. If not, please ask the follow-up questions on [discuss.hashicorp.com](https://discuss.hashicorp.com) where a lot more people will be able to answer.
