### ISSUE TITLE
ELB Log Delivery Policy does not work in Gov Cloud

### ISSUE THREAD

**Issue by duganth-va** [terraform-aws-modules/terraform-aws-s3-bucket#59]
Looks like the resource ARN would need to be changed for gov cloud to `aws-us-gov`. Any reason the module creates the arn instead of using the ARN from the resource output?

**Comment by antonbabenko** [comment]
[v1.17.0](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/releases/v1.17.0) has been just released.
