### ISSUE TITLE
Creating a bucket with versioning enabled = false sets versioning to suspended

### ISSUE THREAD

**Issue by kevser-m** [terraform-aws-modules/terraform-aws-s3-bucket#61]
I created a bucket with the following config:

```
  versioning = {
    enabled = false
  }
```

In the s3 console the versioning appears as suspended as opposed to disabled.

This led to confusion on my part because a file I uploaded and deleted somehow get saved as a version even though I had specified `enabled = false`.

**Comment by bryantbiggs** [comment]
this is what AWS sets - once versioning is set, you can only ever suspend it, not remove it
