### ISSUE TITLE
Any support for storage class analysis?

### ISSUE THREAD

**Issue by vainkop** [terraform-aws-modules/terraform-aws-s3-bucket#65]
Is there any support for storage class analysis?
https://docs.aws.amazon.com/AmazonS3/latest/user-guide/configure-analytics-storage-class.html

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_analytics_configuration

Thanks

**Comment by bryantbiggs** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_analytics_configuration

**Comment by vainkop** [comment]
> https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_analytics_configuration

The issue is not new & you posted the same link as in my original message :) https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/65#issue-809203709

I don't bremember exactly already but I assume that the support for s3_bucket_analytics_configuration wasn't present in this module?

**Comment by bryantbiggs** [comment]
apologies, I saw the first link to aws docs and was just posting the resource reference so that both myself and others know the resource exists if anyone wants to pickup this PR

**Comment by vainkop** [comment]
> apologies, I saw the first link to aws docs and was just posting the resource reference so that both myself and others know the resource exists if anyone wants to pickup this PR

It's ok :)

I probably forked the module & added what was missing at the time when I created this issue & didn't have time to create pr here...
