### ISSUE TITLE
Add a warning in the Complete example about the object lock feature

### ISSUE THREAD

**Issue by Feliksas** [terraform-aws-modules/terraform-aws-s3-bucket#67]
Greetings,
Please somehow annotate or highlight the very dangerous option `object_lock_configuration` in the full S3 example, or change the default retention mode to GOVERNANCE at least, so that other people don't find themselves in the situation that I've got myself into  - I wasn't quite aware of this functionality and forgot to remove it from my configuration, which was based on this example. In short - now I'm stuck with a couple buckets which no one (even support) can delete for the next 5 years.

**Comment by antonbabenko** [comment]
That is too bad to hear. My apologies for this.

I have just updated the example in 8085fb17ca9bed3b5f7656ef3fc0cb217c5f8ee6
