### ISSUE TITLE
Add possibility to retain bucket when destroying the resource 

### ISSUE THREAD

**Issue by rjcoelho** [terraform-aws-modules/terraform-aws-s3-bucket#83]
Because if for some reason/mistake, I destroy the resource, I want to retain the bucket (its the user data)
Just expose the lifecycle meta-arg, or the prevent_destroy flag
Keep it to false by default
Thanks

**Comment by antonbabenko** [comment]
Duplicate.

https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/issues/33#issuecomment-821526135

**Comment by rjcoelho** [comment]
lifecycle {
prevent_destroy = true
}

Can I pass this to the module ?

**Comment by antonbabenko** [comment]
No, it is not supported in the modules but only on individual resources, and it is not possible to use any variables there.

https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#prevent_destroy
