### ISSUE TITLE
Add support for NLB access logs

### ISSUE THREAD

**Issue by wiegandf** [terraform-aws-modules/terraform-aws-s3-bucket#93]
## Describe the solution you'd like.
Similar to the attach_elb_log_delivery_policy flag, we could have an attach_nlb_log_delivery_policy flag that would account for https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html#access-logging-bucket-requirements. 

## Describe alternatives you've considered.
Since the module provides the option to attach bucket policies, you can create the policy on your own and attach it to the bucket.

**Comment by antonbabenko** [comment]
Hi @wiegandf !

Along the same lines, there can be support for other log deliveries by other services, such as CloudTrail, Config, etc.

PS: Pull-request is welcome.

**Comment by antonbabenko** [comment]
[v2.4.0](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/releases/v2.4.0) has been just released.
